services:
  - type: web
    name: gg-epspro
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: STOCKS_FILE_PATH
        value: /var/data/stocks.json
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
